### ISSUE TITLE
main-container css in page.html

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#240]
Currently, the `main-container` class is added in `page.html` on every page except `search.index`. This causes some padding to appear before the content of for example the Holding Pen.

Is this legacy already or shall we only use it on the applicable pages?

```css
.main-container {
        padding-top: 50px;
        padding-bottom: 50px;
}
```

The point is that I would not like to use it on the Holding Pen pages.
